# Generated by Django 2.2.16 on 2024-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240607_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
