# Generated by Django 2.2.16 on 2024-06-26 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240618_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscribing_user',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user_to_subscribe',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
