# Generated by Django 2.2.16 on 2024-06-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240626_0705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Follow',
        ),
    ]
