
name: Main Foodgram Workflow
# Перечень событий-триггеров, при которых должен запускаться workflow
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      # Выполняем команду tree в текущей директории
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #flake8-isort
          pip install flake8 pep8-naming flake8-broken-line flake8-return 
          pip install -r ./backend/foodgram/requirements.txt

      - name: Test with flake8 and django tests
        run: |
          python -m flake8
          cd backend/
          python manage.py test 