# Generated by Django 4.2.13 on 2024-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Кол-во ингридиента в рецепте', 'verbose_name_plural': 'Кол-во ингридиента в рецепте'},
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_as_ingredients', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipe_as_tag', to='recipes.tag', verbose_name='Список id тегов'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Уникальное значение'),
        ),
    ]
