# Generated by Django 2.2.16 on 2024-06-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='coocing_time',
        ),
    ]
