# Generated by Django 2.2.16 on 2024-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_coocing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=0, help_text='Введите время приготовления в минутах', verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
