# Generated by Django 4.2.13 on 2024-08-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
