# Generated by Django 4.2.13 on 2024-08-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscriptions_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
